"""Turn a natural-language strategy idea into a backtestable bot.

Safety model: the backtest always runs a **vetted** strategy built from a
parsed :class:`StrategySpec` — model output is never executed. The LLM backend
is used only to author human-readable code (Python for our engine, MQL5 for
MetaTrader) that the user can read, edit, and export.
"""

from __future__ import annotations

import re
from dataclasses import dataclass, field

from ..backtest.library import RsiReversionStrategy, SmaCrossStrategy
from ..backtest.strategy import Strategy
from .base import LLMBackend


@dataclass(frozen=True)
class StrategySpec:
    kind: str                       # "sma_cross" | "rsi_reversion"
    params: dict[str, float] = field(default_factory=dict)
    description: str = ""


def parse_spec(description: str) -> StrategySpec:
    """Deterministically map a description to a vetted strategy spec."""
    text = description.lower()
    ints = [int(n) for n in re.findall(r"\d+", text)]

    if "rsi" in text or "oversold" in text or "mean revert" in text or "mean-revert" in text:
        period = ints[0] if ints else 14
        oversold = next((n for n in ints if n <= 40), 30)
        overbought = next((n for n in ints if 60 <= n <= 90), 70)
        return StrategySpec(
            "rsi_reversion",
            {"period": float(period), "oversold": float(oversold), "overbought": float(overbought)},
            description,
        )

    # Default / explicit moving-average crossover.
    periods = sorted(n for n in ints if 1 < n <= 400)
    fast = periods[0] if periods else 20
    slow = periods[1] if len(periods) > 1 else max(50, fast * 2)
    allow_short = "short" in text
    return StrategySpec(
        "sma_cross",
        {"fast": float(fast), "slow": float(slow), "allow_short": float(allow_short)},
        description,
    )


def build_strategy(spec: StrategySpec) -> Strategy:
    """Instantiate the vetted library strategy for *spec* (safe — no exec)."""
    p = spec.params
    if spec.kind == "rsi_reversion":
        return RsiReversionStrategy(
            period=int(p.get("period", 14)),
            oversold=p.get("oversold", 30.0),
            overbought=p.get("overbought", 70.0),
        )
    return SmaCrossStrategy(
        fast=int(p.get("fast", 20)),
        slow=int(p.get("slow", 50)),
        allow_short=bool(p.get("allow_short", 0.0)),
    )


def python_code(spec: StrategySpec) -> str:
    """Render readable Python source for the strategy (for display/export)."""
    p = spec.params
    if spec.kind == "rsi_reversion":
        return f'''"""RSI mean-reversion bot — generated by KobeFinance Bot Designer."""
from kobefinance.services.backtest.strategy import Strategy, Context, rsi


class GeneratedBot(Strategy):
    name = "rsi_reversion"

    def __init__(self):
        super().__init__()
        self.period, self.oversold, self.overbought = {int(p.get("period",14))}, {p.get("oversold",30.0)}, {p.get("overbought",70.0)}
        self._rsi = []

    def prepare(self, closes):
        self._rsi = rsi(closes, self.period)

    def on_bar(self, ctx: Context):
        value = self._rsi[ctx.index]
        if value is None:
            return
        if value <= self.oversold:   # oversold -> enter long
            ctx.buy()
        elif value >= self.overbought:  # recovered -> exit
            ctx.close()
'''
    short_branch = "ctx.sell()" if p.get("allow_short", 0.0) else "ctx.close()"
    return f'''"""SMA crossover bot — generated by KobeFinance Bot Designer."""
from kobefinance.services.backtest.strategy import Strategy, Context, sma


class GeneratedBot(Strategy):
    name = "sma_cross"

    def __init__(self):
        super().__init__()
        self.fast, self.slow = {int(p.get("fast",20))}, {int(p.get("slow",50))}
        self._fast, self._slow = [], []

    def prepare(self, closes):
        self._fast = sma(closes, self.fast)
        self._slow = sma(closes, self.slow)

    def on_bar(self, ctx: Context):
        f, s = self._fast[ctx.index], self._slow[ctx.index]
        if f is None or s is None:
            return
        if f > s:            # fast above slow -> trend up
            ctx.buy()
        else:                # fast below slow
            {short_branch}
'''


def mql5_code(spec: StrategySpec, symbol: str = "EURUSD") -> str:
    """Render a MetaTrader 5 Expert Advisor for the strategy (for export)."""
    p = spec.params
    if spec.kind == "rsi_reversion":
        return f'''//+------------------------------------------------------------------+
//| RSI mean-reversion EA — generated by KobeFinance Bot Designer     |
//+------------------------------------------------------------------+
#include <Trade/Trade.mqh>
CTrade trade;
input int    RsiPeriod  = {int(p.get("period",14))};
input double Oversold   = {p.get("oversold",30.0)};
input double Overbought = {p.get("overbought",70.0)};
input double Lots       = 0.10;
int rsiHandle;

int OnInit() {{ rsiHandle = iRSI(_Symbol, _Period, RsiPeriod, PRICE_CLOSE); return INIT_SUCCEEDED; }}

void OnTick() {{
   double r[]; if(CopyBuffer(rsiHandle, 0, 0, 1, r) <= 0) return;
   bool hasPos = PositionSelect(_Symbol);
   if(r[0] <= Oversold && !hasPos)        trade.Buy(Lots, _Symbol);
   else if(r[0] >= Overbought && hasPos)  trade.PositionClose(_Symbol);
}}
'''
    close_or_short = (
        "if(PositionSelect(_Symbol)) trade.PositionClose(_Symbol);\n      trade.Sell(Lots, _Symbol);"
        if p.get("allow_short", 0.0)
        else "if(PositionSelect(_Symbol)) trade.PositionClose(_Symbol);"
    )
    return f'''//+------------------------------------------------------------------+
//| SMA crossover EA — generated by KobeFinance Bot Designer          |
//+------------------------------------------------------------------+
#include <Trade/Trade.mqh>
CTrade trade;
input int    FastPeriod = {int(p.get("fast",20))};
input int    SlowPeriod = {int(p.get("slow",50))};
input double Lots       = 0.10;
int fastHandle, slowHandle;

int OnInit() {{
   fastHandle = iMA(_Symbol, _Period, FastPeriod, 0, MODE_SMA, PRICE_CLOSE);
   slowHandle = iMA(_Symbol, _Period, SlowPeriod, 0, MODE_SMA, PRICE_CLOSE);
   return INIT_SUCCEEDED;
}}

void OnTick() {{
   double f[], s[];
   if(CopyBuffer(fastHandle,0,0,1,f) <= 0 || CopyBuffer(slowHandle,0,0,1,s) <= 0) return;
   if(f[0] > s[0]) {{
      if(!PositionSelect(_Symbol)) trade.Buy(Lots, _Symbol);
   }} else {{
      {close_or_short}
   }}
}}
'''


@dataclass
class DesignResult:
    spec: StrategySpec
    strategy: Strategy
    python_code: str
    mql5_code: str
    backend_name: str
    rationale: str = ""


_SYSTEM = (
    "You are a quantitative trading strategy engineer. Given a strategy idea, "
    "write a concise Python class subclassing our Strategy API (indicators: sma, "
    "ema, rsi; methods ctx.buy()/ctx.sell()/ctx.close()). Output only code."
)


def design(description: str, backend: LLMBackend, symbol: str = "EURUSD") -> DesignResult:
    """Produce a backtestable strategy plus readable code for *description*."""
    spec = parse_spec(description)
    strategy = build_strategy(spec)

    # The vetted, deterministic code is what we run and display by default.
    py = python_code(spec)
    mql5 = mql5_code(spec, symbol)

    rationale = ""
    # If a real model backend is configured, let it author an alternative
    # write-up / rationale for the user to read (not executed).
    if backend.name.startswith(("Ollama", "llama", "Claude")):
        try:
            rationale = backend.generate(
                f"Strategy idea: {description}\n\nExplain the approach and risks in 4-6 lines.",
                system=_SYSTEM,
            )
        except Exception as exc:  # network/model errors shouldn't break design
            rationale = f"(LLM rationale unavailable: {exc})"

    return DesignResult(
        spec=spec,
        strategy=strategy,
        python_code=py,
        mql5_code=mql5,
        backend_name=backend.name,
        rationale=rationale,
    )
